Repository buildkite/agent, pull requests merged in 2023-03, with the labels that each got.

#1989 Apply suggestions from buildkite/docs#1902
  clicommand/bootstrap.go
  clicommand/oidc_request_token.go
Labels: documentation

#2003 Add tags from env variables provided by the controller in agent-stack-k8s if kuberenetes-exec experiment is enabled
  agent/k8s_tags.go
  agent/k8s_tags_test.go
  agent/tags.go
Labels: kubernetes

#2025 PDP-581 added agent support for getting the meta-data by build
  agent/api.go
  api/meta_data.go
  clicommand/meta_data_exists.go
  clicommand/meta_data_get.go
  clicommand/meta_data_keys.go
Labels: Good to go
