Repository buildkite/agent, pull requests merged in 2023-08, with the labels that each got.

#2264 Fix scalar plugin parsing
  internal/pipeline/parser_test.go
  internal/pipeline/plugin.go
  internal/pipeline/plugins.go
Labels: bug, yaml

#2265 Fix data race in testAgentEndpoint
  agent/integration/job_runner_integration_test.go
Labels: quality of life

#2210 Verify step signatures
  agent/agent_configuration.go
  agent/integration/job_runner_integration_test.go
  agent/integration/job_verification_integration_test.go
  agent/integration/test_helpers.go
  agent/job_runner.go
  agent/run_job.go
  agent/verify_job.go
  api/jobs.go
  clicommand/agent_start.go
  internal/pipeline/json.go
  internal/pipeline/json_test.go
  internal/pipeline/sign.go
  internal/pipeline/sign_test_helpers.go
  internal/pipeline/step_command.go
  internal/pipeline/steps.go
Labels: signing

#2279 Add ordered.Unmarshal, and use it
  internal/ordered/unmarshal.go
  internal/ordered/unmarshal_test.go
  internal/pipeline/parser.go
  internal/pipeline/parser_test.go
  internal/pipeline/pipeline.go
  internal/pipeline/plugins.go
  internal/pipeline/sign.go
  internal/pipeline/step.go
  internal/pipeline/step_command.go
  internal/pipeline/step_group.go
  internal/pipeline/step_input.go
  internal/pipeline/step_trigger.go
  internal/pipeline/step_unknown.go
  internal/pipeline/step_wait.go
  internal/pipeline/steps.go
Labels: yaml

#2292 Include plugins in command step signatures
  agent/integration/job_verification_integration_test.go
  api/jobs.go
  internal/pipeline/sign.go
  internal/pipeline/sign_test.go
  internal/pipeline/step_command.go
Labels: signing

#2319 Fix signature mismatches when steps have plugins
  agent/integration/job_verification_integration_test.go
  clicommand/agent_start.go
  internal/ordered/unmarshal.go
  internal/ordered/unmarshal_test.go
  internal/pipeline/parser_test.go
  internal/pipeline/plugin.go
  internal/pipeline/plugin_test.go
  internal/pipeline/plugins.go
  internal/pipeline/sign_test.go
  internal/pipeline/step_command.go
  internal/pipeline/step_command_test.go
Labels: yaml
